name: Lines of Code

on:
  push:
    branches: [mehran]
  pull_request:
    branches: [main]

jobs:
  cloc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Count the lines
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: False
          directory: ./
          badge: cloc.svg
          ignore: 'README|*.png'
  
      - name: Commit badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Lines of Code badge - ${{ steps.badge.outputs.total_lines }}
          push_options: '--force'
